// <auto-generated />
using System;
using GhazaSystem.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GhazaSystem.Api.Migrations
{
    [DbContext(typeof(GhazaDbContext))]
    [Migration("20251216112449_Plan-A-7")]
    partial class PlanA7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Daily_FoodUser", b =>
                {
                    b.Property<Guid>("Daily_FoodsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("usersId")
                        .HasColumnType("uuid");

                    b.HasKey("Daily_FoodsId", "usersId");

                    b.HasIndex("usersId");

                    b.ToTable("Daily_FoodUser");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Daily_Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Mount")
                        .HasColumnType("integer");

                    b.Property<Guid>("foodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("foodId");

                    b.ToTable("Daily_Foods");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Food_Change", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Food_ChangedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type_of_changes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Food_ChangedId");

                    b.HasIndex("LoginId");

                    b.ToTable("Food_Change");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Ip_Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<long>("National_Code")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Daily_FoodUser", b =>
                {
                    b.HasOne("GhazaSystem.Common.Data.Daily_Food", null)
                        .WithMany()
                        .HasForeignKey("Daily_FoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhazaSystem.Common.Data.User", null)
                        .WithMany()
                        .HasForeignKey("usersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Daily_Food", b =>
                {
                    b.HasOne("GhazaSystem.Common.Data.Food", "food")
                        .WithMany()
                        .HasForeignKey("foodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("food");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Food_Change", b =>
                {
                    b.HasOne("GhazaSystem.Common.Data.Daily_Food", "Food_Changed")
                        .WithMany()
                        .HasForeignKey("Food_ChangedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GhazaSystem.Common.Data.Login", null)
                        .WithMany("Food_Changes")
                        .HasForeignKey("LoginId");

                    b.Navigation("Food_Changed");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Login", b =>
                {
                    b.HasOne("GhazaSystem.Common.Data.User", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.Login", b =>
                {
                    b.Navigation("Food_Changes");
                });

            modelBuilder.Entity("GhazaSystem.Common.Data.User", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
